import {db,auth} from './firebase.js';
import {doc,onSnapshot,runTransaction,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
const ref=doc(db,'learning_resources_app','main'),PERIODS=['الأولى','الثانية','الثالثة','الرابعة','الخامسة','السادسة','السابعة','الثامنة'];let state={bookings:[],blocks:[],managers:{}};const $=id=>document.getElementById(id),today=()=>{const d=new Date;d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)},flash=(t,bad=false)=>{const el=$('msg');el.textContent=t;el.style.background=bad?'#b91c1c':'#065f46';el.style.display='block';clearTimeout(el.t);el.t=setTimeout(()=>el.style.display='none',2600)},safe=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
PERIODS.forEach((x,i)=>$('blockPeriod').insertAdjacentHTML('beforeend',`<option value="${i+1}">الحصة ${x}</option>`));
onAuthStateChanged(auth,u=>{if(!u)location.replace('./admin-login.html');else $('userEmail').textContent=u.email||''});$('logout').onclick=()=>signOut(auth);
async function mutate(fn){await runTransaction(db,async tx=>{const snap=await tx.get(ref),data=snap.exists()?snap.data():{};fn(data);tx.set(ref,{...data,updatedAt:serverTimestamp()},{merge:true})})}
onSnapshot(ref,s=>{state=s.exists()?s.data():state;state.bookings=Array.isArray(state.bookings)?state.bookings:[];state.blocks=Array.isArray(state.blocks)?state.blocks:[];state.managers=state.managers||{};render()},e=>flash(`تعذر تحديث اللوحة: ${e.code||'خطأ اتصال'}`,true));
$('blockForm').onsubmit=async e=>{e.preventDefault();try{await mutate(d=>{d.blocks=d.blocks||[];d.blocks.push({id:crypto.randomUUID(),hall:$('blockHall').value,date:$('blockDate').value,period:Number($('blockPeriod').value)||'',reason:$('blockReason').value.trim(),active:true})});e.target.reset();flash('تم حفظ الإغلاق')}catch(err){flash(`تعذر حفظ الإغلاق: ${err.code||''}`,true)}};
$('managerForm').onsubmit=async e=>{e.preventDefault();try{await mutate(d=>{d.managers=d.managers||{};d.managers[$('managerHall').value]={name:$('managerName').value.trim(),email:$('managerEmail').value.trim(),phone:$('managerPhone').value.trim()}});flash('تم حفظ بيانات المسؤول')}catch(err){flash(`تعذر الحفظ: ${err.code||''}`,true)}};
function render(){const blocks=$('blocks'),managers=$('managers');blocks.innerHTML=state.blocks.length?state.blocks.map(b=>`<p>${safe(b.hall||'كل القاعات')} | ${safe(b.date||'كل التواريخ')} | ${b.period?'الحصة '+safe(PERIODS[b.period-1]):'كل الحصص'} | ${safe(b.reason||'')} <button class="danger" data-block="${safe(b.id)}">حذف</button></p>`).join(''):'<p>لا توجد إغلاقات.</p>';managers.innerHTML=Object.entries(state.managers).map(([h,m])=>`<p><b>${safe(h)}</b>: ${safe(m.name||'')} ${m.email?`| ${safe(m.email)}`:''} ${m.phone?`| ${safe(m.phone)}`:''}</p>`).join('')||'<p>لم تسجل بيانات مسؤولين.</p>';renderBookings()}
$('blocks').onclick=async e=>{const id=e.target.dataset.block;if(id&&confirm('حذف هذا الإغلاق؟'))try{await mutate(d=>d.blocks=(d.blocks||[]).filter(x=>x.id!==id));flash('تم حذف الإغلاق')}catch(err){flash('تعذر حذف الإغلاق',true)}};
function filtered(){const q=$('search').value.trim().toLowerCase(),t=today(),mode=$('status').value,date=$('filterDate').value,hall=$('filterHall').value;return [...state.bookings].filter(b=>{const statusOk=mode==='all'||(mode==='today'?b.date===t:mode==='future'?b.date>=t:b.date<t);const qOk=!q||[b.hall,b.teacher,b.bookingType,b.subject,b.grade,b.section,b.date].join(' ').toLowerCase().includes(q);return statusOk&&qOk&&(!date||b.date===date)&&(!hall||b.hall===hall)}).sort((a,b)=>b.date.localeCompare(a.date)||Number(a.period)-Number(b.period))}
function renderBookings(){const list=filtered();$('allCount').textContent=state.bookings.length;$('todayCount').textContent=state.bookings.filter(b=>b.date===today()).length;$('shownCount').textContent=list.length;$('bookingRows').innerHTML=list.map(b=>`<tr class="${b.date===today()?'today-row':''}"><td>${safe(b.date)}</td><td>${safe(b.hall||'')}</td><td>${safe(PERIODS[b.period-1]||b.period)}</td><td>${safe(b.teacher||'')}</td><td>${b.bookingType==='admin'?'حجز الإدارة':'تعليمي'}</td><td>${b.bookingType==='admin'?'—':`${safe(b.grade||'')}/${safe(b.section||'')}`}</td><td>${safe(b.subject||'')}</td><td><button data-edit="${safe(b.id)}">تعديل</button> <button class="danger" data-delete="${safe(b.id)}">حذف</button></td></tr>`).join('')||'<tr><td colspan="8">لا توجد نتائج مطابقة.</td></tr>'}
['search','status','filterDate','filterHall'].forEach(id=>$(id).addEventListener(id==='search'?'input':'change',renderBookings));$('clearFilters').onclick=()=>{$('search').value='';$('status').value='all';$('filterDate').value='';$('filterHall').value='';renderBookings()};
$('bookingRows').onclick=async e=>{const id=e.target.dataset.delete||e.target.dataset.edit;if(!id)return;const b=state.bookings.find(x=>String(x.id)===String(id));if(!b)return;if(e.target.dataset.delete){if(!confirm(`هل تريد حذف حجز ${b.teacher||''} بتاريخ ${b.date}؟`))return;try{await mutate(d=>d.bookings=(d.bookings||[]).filter(x=>String(x.id)!==String(id)));flash('تم حذف الحجز')}catch(err){flash(`تعذر حذف الحجز: ${err.code||''}`,true)}}else{const teacher=prompt('اسم المعلم',b.teacher||'');if(teacher===null)return;const date=prompt('التاريخ YYYY-MM-DD',b.date||'');if(date===null)return;const period=Number(prompt('رقم الحصة 1-8',b.period));if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||period<1||period>8){flash('التاريخ أو رقم الحصة غير صالح',true);return}try{await mutate(d=>{const x=(d.bookings||[]).find(x=>String(x.id)===String(id));if(x)Object.assign(x,{teacher:teacher.trim(),date,period})});flash('تم تعديل الحجز')}catch(err){flash(`تعذر التعديل: ${err.code||''}`,true)}}};
function exportData(){return filtered().map(b=>({'التاريخ':b.date,'القاعة':b.hall||'','الحصة':PERIODS[b.period-1]||b.period,'المعلم/الجهة':b.teacher||'','نوع الحجز':b.bookingType==='admin'?'حجز الإدارة':'تعليمي','المادة':b.subject||'','الصف':b.bookingType==='admin'?'':b.grade||'','الشعبة':b.bookingType==='admin'?'':b.section||''}))}
$('excel').onclick=()=>{const rows=exportData();if(!rows.length){flash('لا توجد نتائج لتصديرها',true);return}if(!window.XLSX){flash('تعذر تحميل مكتبة Excel',true);return}const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);ws['!cols']=[{wch:14},{wch:24},{wch:14},{wch:24},{wch:16},{wch:22},{wch:10},{wch:10}];XLSX.utils.book_append_sheet(wb,ws,'الحجوزات');XLSX.writeFile(wb,`حجوزات-${today()}.xlsx`);flash('تم إنشاء ملف Excel')};
$('pdf').onclick=()=>{const rows=exportData();if(!rows.length){flash('لا توجد نتائج لتصديرها',true);return}const jspdf=window.jspdf;if(!jspdf?.jsPDF){flash('تعذر تحميل مكتبة PDF',true);return}const doc=new jspdf.jsPDF({orientation:'landscape'});doc.setFontSize(14);doc.text(`Bookings Report - ${today()}`,14,15);doc.autoTable({startY:22,head:[['Date','Hall','Period','Teacher/Entity','Booking Type','Subject','Grade','Section']],body:rows.map(r=>[r['التاريخ'],r['القاعة'],r['الحصة'],r['المعلم/الجهة'],r['نوع الحجز'],r['المادة'],r['الصف'],r['الشعبة']]),styles:{fontSize:9,halign:'center'},headStyles:{fillColor:[15,122,58]}});doc.save(`bookings-${today()}.pdf`);flash('تم إنشاء ملف PDF')};
