import {db,auth} from './firebase.js';
import {doc,onSnapshot,runTransaction,serverTimestamp} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js';
import {onAuthStateChanged,signOut} from 'https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js';
const ref=doc(db,'learning_resources_app','main'), PERIODS=['الأولى','الثانية','الثالثة','الرابعة','الخامسة','السادسة','السابعة','الثامنة'];let state={bookings:[],blocks:[],managers:{}};const $=id=>document.getElementById(id),today=()=>{const d=new Date;d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)},flash=t=>{msg.textContent=t;msg.style.display='block';setTimeout(()=>msg.style.display='none',2200)};PERIODS.forEach((x,i)=>blockPeriod.insertAdjacentHTML('beforeend',`<option value="${i+1}">الحصة ${x}</option>`));
onAuthStateChanged(auth,u=>{if(!u)location.replace('./admin-login.html');else userEmail.textContent=u.email||''});logout.onclick=()=>signOut(auth);
async function mutate(fn){await runTransaction(db,async tx=>{const snap=await tx.get(ref);const data=snap.exists()?snap.data():{};fn(data);tx.set(ref,{...data,updatedAt:serverTimestamp()},{merge:true})})}
onSnapshot(ref,s=>{state=s.exists()?s.data():state;state.bookings=state.bookings||[];state.blocks=state.blocks||[];state.managers=state.managers||{};render()});
blockForm.onsubmit=async e=>{e.preventDefault();await mutate(d=>{d.blocks=d.blocks||[];d.blocks.push({id:crypto.randomUUID(),hall:blockHall.value,date:blockDate.value,period:Number(blockPeriod.value)||'',reason:blockReason.value.trim(),active:true})});blockForm.reset();flash('تم حفظ الإغلاق')};
managerForm.onsubmit=async e=>{e.preventDefault();await mutate(d=>{d.managers=d.managers||{};d.managers[managerHall.value]={name:managerName.value.trim(),email:managerEmail.value.trim(),phone:managerPhone.value.trim()}});flash('تم حفظ بيانات المسؤول')};
function render(){blocks.innerHTML=state.blocks.length?state.blocks.map(b=>`<p>${b.hall||'كل القاعات'} | ${b.date||'كل التواريخ'} | ${b.period?'الحصة '+PERIODS[b.period-1]:'كل الحصص'} | ${b.reason||''} <button class="danger" data-block="${b.id}">حذف</button></p>`).join(''):'<p>لا توجد إغلاقات.</p>';managers.innerHTML=Object.entries(state.managers).map(([h,m])=>`<p><b>${h}</b>: ${m.name||''} ${m.email?`| ${m.email}`:''} ${m.phone?`| ${m.phone}`:''}</p>`).join('')||'<p>لم تسجل بيانات مسؤولين.</p>';renderBookings()}
blocks.onclick=async e=>{const id=e.target.dataset.block;if(id){await mutate(d=>d.blocks=(d.blocks||[]).filter(x=>x.id!==id));flash('تم حذف الإغلاق')}};
function filtered(){const q=search.value.trim(),t=today();return [...state.bookings].filter(b=>(status.value==='all'||(status.value==='future'?b.date>=t:b.date<t))&&(!q||JSON.stringify(b).includes(q))).sort((a,b)=>b.date.localeCompare(a.date)||a.period-b.period)}
function renderBookings(){bookingRows.innerHTML=filtered().map(b=>`<tr><td>${b.date}</td><td>${b.hall||''}</td><td>${PERIODS[b.period-1]||b.period}</td><td>${b.teacher||''}</td><td>${b.grade||''}/${b.section||''}</td><td>${b.subject||''}</td><td><button data-edit="${b.id}">تعديل</button> <button class="danger" data-delete="${b.id}">حذف</button></td></tr>`).join('')||'<tr><td colspan="7">لا توجد نتائج.</td></tr>'}search.oninput=renderBookings;status.onchange=renderBookings;
bookingRows.onclick=async e=>{const id=e.target.dataset.delete||e.target.dataset.edit;if(!id)return;const b=state.bookings.find(x=>String(x.id)===id);if(e.target.dataset.delete){if(confirm('حذف هذا الحجز؟'))await mutate(d=>d.bookings=(d.bookings||[]).filter(x=>String(x.id)!==id))}else{const teacher=prompt('اسم المعلم',b.teacher);if(teacher===null)return;const date=prompt('التاريخ YYYY-MM-DD',b.date);if(date===null)return;const period=Number(prompt('رقم الحصة 1-8',b.period));await mutate(d=>{const x=(d.bookings||[]).find(x=>String(x.id)===id);Object.assign(x,{teacher:teacher.trim(),date,period})})}};
function reportRows(){const t=new Date(today()+'T00:00:00'),mode=range.value;return state.bookings.filter(b=>{if(mode==='all')return true;const d=new Date(b.date+'T00:00:00');if(mode==='day')return b.date===today();if(mode==='month')return d.getFullYear()===t.getFullYear()&&d.getMonth()===t.getMonth();const start=new Date(t);start.setDate(t.getDate()-t.getDay());const end=new Date(start);end.setDate(start.getDate()+6);return d>=start&&d<=end})}
csv.onclick=()=>{const rows=[['التاريخ','القاعة','الحصة','المعلم','المادة','الصف','الشعبة'],...reportRows().map(b=>[b.date,b.hall,b.period,b.teacher,b.subject,b.grade,b.section])];const csvText='\ufeff'+rows.map(r=>r.map(v=>`"${String(v??'').replaceAll('"','""')}"`).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csvText],{type:'text/csv;charset=utf-8'}));a.download='bookings-report.csv';a.click();URL.revokeObjectURL(a.href)};
print.onclick=()=>{const rows=reportRows().map(b=>`<tr><td>${b.date}</td><td>${b.hall}</td><td>${PERIODS[b.period-1]}</td><td>${b.teacher}</td><td>${b.grade}/${b.section}</td><td>${b.subject}</td></tr>`).join('');const w=open('','_blank');w.document.write(`<html dir="rtl"><head><title>تقرير الحجوزات</title><style>body{font-family:Arial}table{width:100%;border-collapse:collapse}td,th{border:1px solid #999;padding:8px}</style></head><body><h1>تقرير الحجوزات</h1><table><tr><th>التاريخ</th><th>القاعة</th><th>الحصة</th><th>المعلم</th><th>الصف</th><th>المادة</th></tr>${rows}</table><script>print()<\/script></body></html>`);w.document.close()};
